### PR TITLE
Merging events data from the parent to the child

### PR DESCRIPTION
**Pull request by darrencauthon**
screenshot_012019_111442_pm

### CODE REVIEW

**Comment by darrencauthon** [comment]
I don't know the right word to use... I'm not a fan of "merge_mode" but I don't know what else to call it.

The purpose of this is to allow us to continually flow data from the parent event to the child.  Trust me, this has applications, I already need it for my demo.

**Comment by calebcauthon** [comment]
this seems like a no brainer. no need for 'trust me'...

**Comment by calebcauthon** [comment]
I'm actually wondering why it's a mode. it might as well be the default behavior. and the exceptional case is where you have data you *dont* want to be made available.

In cases where child elements dont *need* the data, they can ignore it. so I say merge mode is the default for now until we have a use case otherwise.

**Comment by darrencauthon** [comment]
@calebcauthon 

> In cases where child elements dont _need_ the data, they can ignore it. so I say merge mode should be the default for now until we have a use case otherwise.

There will be cases where an event will trigger something that we do not want a merge, like.... if we convert an event with data like ``` { apple: "orange" } ``` which is used to make a GET call, which will return ``` { body: "{name: \"happy\"}", apple: "orange" } ``` which will be passed to the json handler which will then return ``` { body: "{name: \"happy\"}", apple: "orange", name: "happy" } ``` and so on and so on.

See how the events just keep getting larger?  I can imagine someone wanting a final event that's just ``` { name: "happy" }``` because that's what they were trying to get in the first place.

I'm ok with defaulting this "merge mode = merge" in the UI, but not in the code itself.

**Pull request merged**
